swagger: "2.0"
info:
  version: "0.0.1"
  title: Toeic
# during dev, should point to your local machine
# host: 139.59.190.205:8000

host: localhost:8000
# basePath prefixes all resource paths 
basePath: /api
# 
securityDefinitions:
  auth0:
    type: apiKey
    name: Authorization
    in: header
    description: "Authorization logged to application"
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
tags:
- name: "questionReadingTest"
  description: "Everything about question reading test have managed by admin"


produces:
  - application/json
paths:
  /blankQuestion:
    x-swagger-router-controller: questions_reading_test
    post:
      tags:
        - questionReadingTest
      description: admin has logged in, and use import questions of part 5 in the exam. We have received the result include id, content_question, pos, part, level, position blank.
      operationId: importBlankQuestion
      security:
        - auth0: []
      parameters:
        - in: body
          name: body
          description: parameters is json object such as {
            question_content, answer, right_answer, level, part} .
          schema:
            $ref: '#/definitions/ImportBlankQuestion'     # <----------
      responses:
        "200":
          description: Return a question object has imported in DB
          schema:
            type: object
            properties:
              _id:
                type: integer
                description: The user ID.
              question_content:
                type: string
              pos:
                type: integer
              answers:
                type: object
                properties:
                  optA:
                    type: string
                  optB:
                    type: string
                  optC:
                    type: string
                  optD:
                    type: string
              level: 
                type: integer
              part: 
                type: integer
            example: #sample object
              question_content: This is new app for practise toeic.
              pos: 2
              answers:
                  optA: a
                  optB: an
                  optC: one
                  optD: two
              level: 1
              part: 5
              _id: 5c9c86aef41bf82ed47ac679
        "401":
          description: Import Fail
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Import Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      description: Returns all question
      operationId: getAllQuestionPart5
      tags:
        - questionReadingTest
      security:
        - auth0: []
      parameters:
        - in: query
          name: limit
          type: integer
          description: limit record return
        - in: query
          name: page
          type: integer
          description: page you need to get
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MessageResp"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /blankParagraphandQuestion:
    x-swagger-router-controller: questions_reading_test
    post:
      tags:
        - questionReadingTest
      description: admin has logged in, and use import paragraph has blank and array options in the exam. We have received the result include id, content_question, pos, part, level, position blank.
      operationId: importParagraphQuestionPart6
      security:
        - auth0: []
      parameters:
        - in: body
          name: body
          description: parameters is json object include blank paragraph, list options, list right answer, level of paragraph, and part.
          schema:
            $ref: '#/definitions/ImportParagraphQuestionPart6'     # <----------
      responses:
        "200":
          description: Return a paragraph object and list options have imported in DB
          schema:
            type: object
            properties:
              _id:
                type: integer
                description: The record ID.
              blank_paragraph:
                type: string
              list_position:
                type: array
                items:
                  type: integer
              level: 
                type: integer
              part: 
                type: integer
            example: #sample object
              blank_paragraph: This is new app for practise toeic.
              list_position: [7, 16]
              level: 1
              part: 6
              _id: 5c9c86aef41bf82ed47ac679
        "401":
          description: Import Fail
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Import Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /paragraphPart7:
    x-swagger-router-controller: questions_reading_test
    post:
      tags:
        - questionReadingTest
      description: admin has logged in, and use import paragraphs in part 7.
      operationId: importParagraphPart7
      security:
        - auth0: []
      parameters:
        - in: body
          name: body
          description: parameters is json object include paragraphs we need to import.
          schema:
            $ref: '#/definitions/ImportParagraphPart7'     # <----------
      responses:
        "200":
          description: Return a id record pf paragraphs have imported in DB
          schema:
            type: object
            properties:
              _id:
                type: integer
                description: The record ID.
              level: 
                type: integer
              part: 
                type: integer
            example: #sample object
              level: 1
              part: 7
              _id: 5c9c86aef41bf82ed47ac679
        "401":
          description: Import Fail
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Import Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /questionPart7:
    x-swagger-router-controller: questions_reading_test
    post:
      tags:
        - questionReadingTest
      description: admin has logged in, and use import question of the paragraph have imported in part 7.
      operationId: importQuestionsPart7
      security:
        - auth0: []
      parameters:
        - in: body
          name: body
          description: parameters is json object include question, options, right answer, level, part, id_paragraph and explain right answer we need to import.
          schema:
            $ref: '#/definitions/ImportQuestionPart7'     # <----------
      responses:
        "200":
          description: Return a id record question have imported in DB
          schema:
            type: object
            properties:
              _id:
                type: integer
                description: The record ID.
              level: 
                type: integer
              part: 
                type: integer
            example: #sample object
              level: 1
              part: 7
              _id: 5c9c86aef41bf82ed47ac679
        "401":
          description: Import Fail
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Import Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    required:
      - messageError
    properties:
      messageError:
        type: string
  ImportBlankQuestion:
    type: object
    required:
      - question_content
      - answers
      - right_answer
      - explain
      - level
      - part
    properties:
      question_content:
        type: string
      answers:
        type: object
        properties:
          optA:
            type: string
          optB:
            type: string
          optC:
            type: string
          optD:
            type: string
      right_answer: 
        type: string
      explain:
        type: string      
      level: 
        type: integer
      part: 
        type: integer
    example: #sample object
      question_content: This is __ new app for practise toeic.
      answers:
          optA: a
          optB: an
          optC: one
          optD: two
      right_answer: optA
      explain: We need a article in front of Noun
      level: 1
      part: 5
  ImportParagraphQuestionPart6:
    type: object
    required:
      - blank_paragraph
      - list_options
      - list_right_answers
      - list_explains
      - level
      - part
    properties:
      blank_paragraph:
        type: string
      list_options:
        type: array
        items:
          type: object
          properties:
            optA:
              type: string
            optB:
              type: string
            optC:
              type: string
            optD:
              type: string
      list_right_answers:
        type: array
        items:
          type: string
      list_explains:
        type: array
        items:
          type: string
      level:
        type: integer
      part:
        type: integer
    example: #sample object
      blank_paragraph: This is __ new app __ practise toeic.
      list_options: [
        { optA: a, optB: an, optC: one, optD: two},
        { optA: to, optB: for, optC: the, optD: have},
      ]
      list_right_answers: [
        "optA",
        "optB",
      ]
      list_explains: [
        "We need a article in front of Noun",
        "We need a article in front of Noun",
      ]
      level: 1
      part: 6
  ImportParagraphPart7:
    type: object
    required:
      - paragraphs
      - level
      - part
    properties:
      paragraphs:
        type: array
        items:
          type: string
      level:
        type: integer
      part:
        type: integer
    example: #sample object
      paragraphs: [
        "More than 50,000 electronics retailers and distributors are expected at the McCormick Convention Center in Chicago starting next Saturday. Some 1,300 manufacturers from more than 35 countries will exhibit their latest high-technology equipment, including industrial equipment, office machines, and household appliances. 
        The new products won't appear on retailers' shelves until next fall, but show attendees will be able to purchase them during the show at special prices.
        Highlights of the show include the following:
        1. Demonstrations of robots designed for household use. Watch robots perform everyday household chores. Each day, models from a different group of manufacturers will be shown. Hall of Industry, 3:00-5.00 P.M. daily.",
      ]
      level: 1
      part: 7
  ImportQuestionPart7:
    type: object
    required:
      - question_content
      - answers
      - right_answer
      - level
      - part
      - id_paragraph
    properties:
      question_content:
        type: string
      answers:
        type: object
        properties:
          optA:
            type: string
          optB:
            type: string
          optC:
            type: string
          optD:
            type: string
      right_answer: 
        type: string
      explain:
        type: string      
      level: 
        type: integer
      part: 
        type: integer
      id_paragraph:
        type: string
    example: #sample object
      question_content: What is the main topic of the press release ?
      answers:
          optA: The McCormick Convention Center
          optB: Chicago's convention centers 
          optC: Electronics retailers
          optD: The Summer Consumer Electronics Show
      right_answer: optA
      level: 1
      part: 7
      id_paragraph: 5c9c86aef41bf82ed47ac679
  MessageResp:
    type: object
    required: 
      - success
    properties:
      success:
        type: boolean
      message:
        type: string
      value:
        type: object